### ISSUE TITLE
Can't Connect to websocket

### ISSUE THREAD

**Issue by yemistar** [blackhorse-one/stomp_dart_client#10]
When I run your example using 'ws://echo.websocket.org' or my localhost. The websocket is not connecting. If I call stompClient.activate(); and check stompClient.connected it say false. 
here is my code. 

```
  final stompClient = StompClient(
        config: StompConfig(
            url: 'ws://echo.websocket.org',
            onConnect:(StompClient client, StompFrame frame) {

        },
           ));
    stompClient.activate();
    print("${stompClient.connected}");
```

**Comment by KammererTob** [comment]
Hey,

this is because "ws://echo.websocket.org" is not a STOMP endpoint and thus will not perform the necessary handshake with the STOMP Client to be fully connected. 
Also please be aware that the `print("${stompClient.connected}");` after activate will probably be also false for a valid endpoint. You should move this statement inside the `onConnect` callback.

if you have any questions please let me know.

**Comment by KammererTob** [comment]
I am going to close this issue. Feel free to open it again if you feel that your issue is not solved

**Comment by yemistar** [comment]
Sorry for the late reply. I was busy with the virus stuff. You are right. everything works fine now. Thanks
