### ISSUE TITLE
`connectUrl` is re-generated each time when it is called

### ISSUE THREAD

**Issue by MacDeveloper1** [blackhorse-one/stomp_dart_client#95]
The version before `1.0.0` has a `url` value which was initialized once using `SockJsUtils().generateTransportUrl` when `useSockJS` was set to `true`. In next versions you created a getter `connectUrl` which returns the effective transport URL for each connection. I think it should be unique and permanent for new STOMP connection during the session but now `connectUrl` is re-generated each time this getter is called.

**Comment by KammererTob** [comment]
Hi,

according to the SockJS [spec](https://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html#section-36) the session_id needs to be unique for every session:

> Second parameter session_id must be a random string, unique for every session.

So i think this behavior is correct. Do you have a specific issue/use-case as to why you need to be identical? I am not sure if a reconnect should be considered a new session or not, which is the only scenario i currently can think of where the new generation would not be desirable (especially since it can lead to other [issues](https://github.com/blackhorse-one/stomp_dart_client/issues/93))

**Comment by MacDeveloper1** [comment]
Yes. It should be unique for every session but it also should be **permanent** for such session, i.e. value should be **idempotent**.

```dart
final client = StompClient(); // single session
// somewhere on connecting status
print(client.connectUrl); // one value
// somewhere on connected status
print(client.connectUrl); // second value
// somewhere on disconnected status
print(client.connectUrl); // thirdr value
```
But it should be the same as it is the **same** client and **same** session.

Let'say I save websocket clients for some other actions in Map where key is `connectUrl`. Then I never find the value for a key as it always changed.

**Comment by KammererTob** [comment]
Thanks. So if i understand correctly you want to have it return the same value that was used while connecting. So it should only regenerate if it actually is in the process of connecting. Correct? If yes, then that is probably reasonable.

**Comment by MacDeveloper1** [comment]
I created a PR #96. Maybe you can have a quick look if this looks good to you?

**Comment by KammererTob** [comment]
@MacDeveloper1 I have released a new version including this PR
